### ISSUE TITLE
When I try to mixpanel.init I am getting "TypeError: cannot read property 'console' of undefined"

### ISSUE THREAD

**Issue by pawelkontek** [okotoki/figma-mixpanel#2]
![image](https://user-images.githubusercontent.com/7879784/148374864-0bd3ae47-8b20-41c1-8963-8e3d516488e8.png)

**Comment by pawelkontek** [comment]
I was able to avoid the error by installing the full version.

**Comment by trungtin** [comment]
hey @pawelkontek I'm facing the exact same error. What do you mean by installing the full version? Install the `mixpanel-browser@2.32.0`?

And did you init the mixpanel in the main thread or the UI thread?

**Comment by Baffour** [comment]
Also curious @pawelkontek!

**Comment by gb221** [comment]
I solved this by installing the non-reduced version. Can be done with `npm i mixpanel-figma@1.0.0`
